---
title: "Clinical Volume"
---

```{r}
#| label: setup
#| include: false
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(gt)
library(glue)
```

As part of both residency and fellowship training, volume is an important part of both procedural competence and clinical skills. 


```{r}
#| label: download
#| echo: false
source("R/make-anonymous.R", local = knitr::knit_global())
log <- readr::read_csv("anonymous.csv") 

start <- min(log$date, na.rm = TRUE)
stop <- max(log$date, na.rm = TRUE)

# Columns = site | mrn | date | dx1:3 | procedure | location | modifier | notes | special
# Can be broken down into groups based on procedures versus clinical 
procedures <- subset(log, !is.na(procedure)) |>
	rename(type = procedure)
clinical <- subset(log, is.na(procedure))
```

Below is a summary of procedures that have been performed during training.

```{r}
#| label: summary
#| echo: false

# Master list
types <- list(
	cath = c("COR", "RHC", "LHC", "PCI", "pericardiocentesis", "MCS"),
	vascular = c("CVL", "AL", "PIV", "closure"),
	ep = c("DCCV", "CIED", "EPS", "TVP", "ACLS"),
	imaging = c("TTE", "TEE", "stress", "MRI", "CT", "US")
)

# Create categories
cats <- character()
for (i in seq_along(types)) {
	cats <- append(cats, rep(names(types[i]), length(types[[i]])))
}

# Make table
tbl <- tibble(
	category = cats,
	type = unlist(types)
)

# Identifiers of procedure modifiers with categorizations
subtypes <-
	procedures |>
	select(type, location, modifier) 

# Master table
master <- full_join(tbl, subtypes, by = "type")

# Some procedures need specific modifiers, located in the location name
	# Caths -> needs modifier for site
	# TTE -> needs modifier for bedside or not
	# TEE -> needs modifier for if bedside or not
	# EPS -> needs modifier for type
	# DCCV -> modifier for joules, not really needed
	# TVP -> modifier
	# AL/CVL -> lines with locations in modifier

```


```{r}
#| label: counts
#| eval: false

# Specific counts
master |>
	count(category, type, location, modifier)

master |>
	filter(is.na(modifier) & !is.na(location)) |>
	count(category, type, location)

master |>
	filter(is.na(location) & is.na(modifier)) |>
	count(category, type)

master |>
	filter(!is.na(location) & is.na(modifier)) |>
	count(category, type, location)

master |>
	count(type) 

master |>
	count(category)
```	

```{r}
#| label: cocats
#| echo: false
# Required COCATS procedures for fellowship
	# TTE performed (150)
	# TTE interpreted (300)
	# Stress echo (100)
	# TEE performed (50, 100)
	# Nuclear (300)
	# Nuclear injections (35)
	# Cardiac CT interpreted (250)
	# Cardiac CT performed (65)
	# CMR performed (50)
	# CMR interpreted (150)
	# Caths performed (300)
	# TVP performed (5)
	# PPM performed (20, 40)
	# CIED interrogated (100)
	# CIED remote interrogated (25)
	# Cardioversion (20)
	# PCI
	# Pericardiocentesis
	# IABP
	# Impella
	# Other

cocats <- 
	master |>
	filter(
		type == "TTE" & location == "bedside" |
			type == "TTE" & is.na(location) |
			type == "stress" & modifier == "echo" |
			type == "TEE" & location == "bedside" |
			type == "TEE" & is.na(location) |
			type == "stress" & (modifier == "technetium" | modifier == "thallium") |
			type == "CT" |
			type == "CMR" & location == "bedside" |
			type == "CMR" & is.na(location) |
			(type == "RHC" | type == "LHC" | type == "COR") |
			type == "TVP" |
			type == "CIED" & location != "interrogation" |
			type == "CIED" & location == "interrogation" |
			type == "DCCV" |
			type == "PCI" |
			type == "pericardiocentesis" |
			type == "MCS" 
	) |>
	mutate(modifier = case_when(
		type == "COR" ~ NA_character_,
		type == "RHC" ~ NA_character_,
		type == "LHC" ~ NA_character_,
		type == "PCI" ~ NA_character_,
		type == "DCCV" ~ NA_character_,
		type == "MCS" ~ NA_character_,
		type == "CIED" & location == "interrogation" ~ NA_character_,
		type == "CIED" & !location == "interrogation" ~ NA_character_,
		type == "TTE" ~ NA_character_,
		type == "TEE" ~ NA_character_,
		type == "stress" & modifier == "technetium" ~ "nuclear",
		type == "stress" & modifier == "thallium" ~ "nuclear",
		TRUE ~ modifier
	)) |>
	mutate(location = case_when(
		type == "COR" ~ NA_character_,
		type == "RHC" ~ NA_character_,
		type == "LHC" ~ NA_character_,
		type == "PCI" ~ NA_character_,
		type == "pericardiocentesis" ~ NA_character_,
		type == "DCCV" ~ NA_character_,
		type == "MCS" ~ NA_character_,
		type == "CIED" & !location == "interrogation" ~ NA_character_,
		type == "TVP" ~ NA_character_,
		type == "stress" & modifier == "echo" ~ NA_character_,
		type == "stress" & modifier == "nuclear" ~ NA_character_,
		TRUE ~ location
	)) |>
	mutate(type = case_when(
		type %in% c("COR", "RHC", "LHC") ~ "CATH",
		TRUE ~ type
	)) |>
	count(type, location, modifier) 

gt(cocats)
```

