---
title: "Clinical Volume"
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(gt)
```

As part of both residency and fellowship training, volume is an important part of both procedural competence and clinical skills. 

```{r, procedures, echo = FALSE}
# Main log
log <- 
	readxl::read_excel("log.xlsx") %>%
	janitor::clean_names() %>%
	mutate(date = as.Date(date)) %>%
	tibble::as_tibble()

start <- min(log$date, na.rm = TRUE)
stop <- max(log$date, na.rm = TRUE)

# Columns = site | mrn | date | dx1:3 | procedure | location | modifier | notes | special
# Can be broken down into groups based on procedures versus clinical 
procedures <- subset(log, !is.na(procedure))

# Obtain summaries of types
what <- unique(log$procedure)
where <- unique(log$location)

# Some procedures need specific modifiers, located in the location name
	# Caths -> needs modifier for site
	# TTE -> needs modifier for bedside or not
	# TEE -> needs modifier for if bedside or not
	# EPS -> needs modifier for type
	# DCCV -> modifier for joules, not really needed
	# TVP -> modifier
	# AL/CVL -> lines with locations in modifier

types <- c("RHC", "LHC", "PCI", "TEE", "TTE", "DCCV", "stress", "MRI", "TVP", "CIED", "EPS", "pericardiocentesis")

# Summarize
procedures %>%
	filter(procedure %in% types & !is.na(location)) %>%
	group_by(procedure) %>%
	count() %>%
	ungroup() %>%
	gt(rowname_col = "procedure") %>%
	tab_header(
		title = "Procedure Log",
		subtitle = "UIC Cardiology Fellowship"
	) %>%
	tab_source_note(
		source_note = glue::glue("Log from {start} to {stop}")
	) %>%
	tab_stubhead("Procedures") 
```

```{r, clinical, echo = FALSE}
# Columns = site | mrn | date | dx1:3 | procedure | location | modifier | notes | special
# Can be broken down into groups based on procedures versus clinical 
clinical <- subset(log, is.na(procedure))
clinic_types <- unique(clinical$location)

subset(clinical, is.na(location))
```

