---
title: "Atypical AVNRT"
subtitle: Clinical Electrophysiology Conference
author: Anish S. Shah, MD, MS
institute: Division of Cardiology, University of Illinois at Chicago 
date: December 08, 2022
date-format: long
engine: knitr
format:
  revealjs:
    transition: fade
    transition-speed: fast
    slide-number: true
    incremental: false
revealjs-plugins:
  - attribution
jupyter: python3
---

```{r}
#| label: setup
#| echo: false
library(tidyverse)
library(coraline)
library(rhythm)
library(sf)
library(scales)
library(ggsci)

blue <- pal_material("blue", reverse = TRUE)(9)
orange <- pal_material("yellow", reverse = TRUE)(9)
red <- pal_material("pink", reverse = TRUE)(9)
green <- pal_material("teal", reverse = TRUE)(9)
grey <- pal_material("blue-grey", reverse = TRUE)(9)

find_project_folder <- function() {
	x <- sessionInfo()$running
	if (grepl("mac", x)) {
		file.path("/Users", "asshah4", "projects")
	} else if (grepl("Windows", x)) {
		file.path("C:/Users", "asshah4", "projects")
	}
}

loc <- file.path(find_project_folder(), "clinical", "talks", "12-08-22_atypical-avnrt")
```


## Differential

1. Atypical AVNRT
1. Non-reentrant junctional tachycardia (junctional ectopic tachycardia)
1. Non-paroyxsmal junctional tachycardia (d/t digitalis-induced DADs)
1. Dual AV nodal tachycardia (repetitive retrograde concealment or "linking" phenomenon)

## Objectives

1. Review relevant anatomy and physiology of relevant components of conduction system

# Anatomical Structures

# Physiological Properties

# Pathways

# Electrophysiological Concepts

## Evaluation

1. Mode of initiation of tachycardia
1. Atrial activation sequence during tachycardia
1. Influence of bundle branch block on conduction and cycle length during tachycardia
1. Requirement of atria/ventricle for initiation and maintenance of tachcyardia
1. Effect of atrial/ventricular stiulation during tachycardia
1. Effect of drugs or physiological maneuvers on tachycardia

# TODO

- slow-fast pathway
- slow-slow pathway
- fast-slow pathway
- leftward involvement
- connectivity differences
- 2:1 block in AVNRT
- ablative approaches for atypical

# References

## {.smaller}

::: {#refs}
:::